import "./globals.css";
import Navbar from "./components/Navbar";
import PopupLeadForm from "./components/Form";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="h-full antialiased">
      <body className="flex min-h-full flex-col">
        <Navbar />
        {children}
        <PopupLeadForm />
      </body>
    </html>
  );
}
